const repos = [
  {
    "name": "gs-hygen",
    "url": "https://github.com/guidesmiths/gs-hygen",
    "description": null,
    "updatedAt": "2021-09-17T18:11:28.000Z",
    "size": 756,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": "githubActions"
  },
  {
    "name": "react-form-builder",
    "url": "https://github.com/guidesmiths/react-form-builder",
    "description": "React Form Builder",
    "updatedAt": "2021-09-17T08:11:09.000Z",
    "size": 11793,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "rascal",
    "url": "https://github.com/guidesmiths/rascal",
    "description": "A config driven wrapper for amqp.node supporting multi-host connections, automatic error recovery, redelivery flood protection, transparent encryption / decryption and channel pooling.",
    "updatedAt": "2021-09-14T11:52:40.000Z",
    "size": 2352,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": "githubActions"
  },
  {
    "name": "systemic-mongodb",
    "url": "https://github.com/guidesmiths/systemic-mongodb",
    "description": "A systemic mongodb component",
    "updatedAt": "2021-09-14T11:10:50.000Z",
    "size": 1052,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": "githubActions"
  },
  {
    "name": "js-pills",
    "url": "https://github.com/guidesmiths/js-pills",
    "description": "💊  JS pills: a collection of short snippets of javascript for learning purposes",
    "updatedAt": "2021-09-14T09:14:52.000Z",
    "size": 7991,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": "githubActions"
  },
  {
    "name": "systemic-aws-s3",
    "url": "https://github.com/guidesmiths/systemic-aws-s3",
    "description": "systemic-aws-s3",
    "updatedAt": "2021-09-08T13:14:09.000Z",
    "size": 234,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": "githubActions"
  },
  {
    "name": "cybersecurity-handbook",
    "url": "https://github.com/guidesmiths/cybersecurity-handbook",
    "description": "Cybersecurity handbook by GuideSmiths",
    "updatedAt": "2021-09-07T04:09:15.000Z",
    "size": 8760,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "systemic-aws-sqs",
    "url": "https://github.com/guidesmiths/systemic-aws-sqs",
    "description": "systemic-aws-sqs",
    "updatedAt": "2021-08-31T13:17:31.000Z",
    "size": 318,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": "githubActions"
  },
  {
    "name": "marv",
    "url": "https://github.com/guidesmiths/marv",
    "description": "A programmatic database migration tool with plugable drivers for Postgres and MySQL",
    "updatedAt": "2021-08-22T15:55:40.000Z",
    "size": 624,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": "githubActions"
  },
  {
    "name": "marv-mysql-driver",
    "url": "https://github.com/guidesmiths/marv-mysql-driver",
    "description": "A mysql marv driver implementation",
    "updatedAt": "2021-08-22T15:55:34.000Z",
    "size": 595,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "systemic",
    "url": "https://github.com/guidesmiths/systemic",
    "description": "A minimal dependency injection framework",
    "updatedAt": "2021-08-11T17:34:33.000Z",
    "size": 558,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": "githubActions"
  },
  {
    "name": "bambot",
    "url": "https://github.com/guidesmiths/bambot",
    "description": "BambooHR Slack bot publishes company holidays, work anniversaries, first days, birthdays, and who is out each weekday.",
    "updatedAt": "2021-08-03T20:03:04.000Z",
    "size": 502,
    "hasIssues": false,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "mood",
    "url": "https://github.com/guidesmiths/mood",
    "description": "Gauge how your team is feeling. Optimize for happiness.",
    "updatedAt": "2021-07-16T12:23:44.000Z",
    "size": 2260,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "systemic-azure-metrics",
    "url": "https://github.com/guidesmiths/systemic-azure-metrics",
    "description": "A systemic plugin to deal with azure metrics",
    "updatedAt": "2021-07-15T11:45:24.000Z",
    "size": 33,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": "githubActions"
  },
  {
    "name": "systemic-redis",
    "url": "https://github.com/guidesmiths/systemic-redis",
    "description": "A systemic redis component",
    "updatedAt": "2021-07-13T10:57:17.000Z",
    "size": 18,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": "githubActions"
  },
  {
    "name": "git-pills",
    "url": "https://github.com/guidesmiths/git-pills",
    "description": "Git Pills",
    "updatedAt": "2021-07-09T14:40:04.000Z",
    "size": 301,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": "githubActions"
  },
  {
    "name": "app-restaurant-reviews",
    "url": "https://github.com/guidesmiths/app-restaurant-reviews",
    "description": "Mentoring repo related to frontend technologies",
    "updatedAt": "2021-07-08T11:13:38.000Z",
    "size": 4051,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "dangerjs-wrapper",
    "url": "https://github.com/guidesmiths/dangerjs-wrapper",
    "description": "Apply cultural rules during your CI process",
    "updatedAt": "2021-07-05T13:52:39.000Z",
    "size": 1006,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": "githubActions"
  },
  {
    "name": "react-native-ble-plx",
    "url": "https://github.com/guidesmiths/react-native-ble-plx",
    "description": "React Native BLE library",
    "updatedAt": "2021-06-18T10:50:42.000Z",
    "size": 5225,
    "hasIssues": false,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "generator-systemic",
    "url": "https://github.com/guidesmiths/generator-systemic",
    "description": "A yeoman-based template to generate a systemic microservice",
    "updatedAt": "2021-06-18T07:48:25.000Z",
    "size": 1996,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "license-checker",
    "url": "https://github.com/guidesmiths/license-checker",
    "description": null,
    "updatedAt": "2021-05-12T16:52:47.000Z",
    "size": 112,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": "githubActions"
  },
  {
    "name": "worksmith",
    "url": "https://github.com/guidesmiths/worksmith",
    "description": "handled",
    "updatedAt": "2021-05-12T13:33:11.000Z",
    "size": 184,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": "githubActions"
  },
  {
    "name": "ks-web-performance",
    "url": "https://github.com/guidesmiths/ks-web-performance",
    "description": "GS workshop project",
    "updatedAt": "2021-05-11T07:21:22.000Z",
    "size": 13600,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "svc-example",
    "url": "https://github.com/guidesmiths/svc-example",
    "description": "An example microservice",
    "updatedAt": "2021-05-08T18:25:35.000Z",
    "size": 134,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "systemic-aws-mq",
    "url": "https://github.com/guidesmiths/systemic-aws-mq",
    "description": null,
    "updatedAt": "2021-04-22T11:02:27.000Z",
    "size": 1,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "confabulous",
    "url": "https://github.com/guidesmiths/confabulous",
    "description": "Confabulous is a hierarchical, asynchronous config loader and post processor.",
    "updatedAt": "2021-04-18T10:00:57.000Z",
    "size": 614,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": "githubActions"
  },
  {
    "name": "error-handler-module",
    "url": "https://github.com/guidesmiths/error-handler-module",
    "description": "Error handler methods for Node.js app and express middlewares.",
    "updatedAt": "2021-04-11T19:49:03.000Z",
    "size": 695,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": "githubActions"
  },
  {
    "name": "handy-postgres",
    "url": "https://github.com/guidesmiths/handy-postgres",
    "description": "A handy, safe API to deal with common PG operations",
    "updatedAt": "2021-04-08T06:58:23.000Z",
    "size": 964,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "systemic-aws-secrets-manager",
    "url": "https://github.com/guidesmiths/systemic-aws-secrets-manager",
    "description": "systemic-aws-secrets-manager",
    "updatedAt": "2021-03-12T16:03:32.000Z",
    "size": 1,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "systemic-aws-sns",
    "url": "https://github.com/guidesmiths/systemic-aws-sns",
    "description": "systemic-aws-sns",
    "updatedAt": "2021-03-12T16:01:40.000Z",
    "size": 1,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "systemic-azure-bus",
    "url": "https://github.com/guidesmiths/systemic-azure-bus",
    "description": "Systemic adapter for azure bus",
    "updatedAt": "2021-03-05T08:38:29.000Z",
    "size": 671,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "awesome-systemic",
    "url": "https://github.com/guidesmiths/awesome-systemic",
    "description": "Oh yeah! Awesome systemic list 😎",
    "updatedAt": "2021-03-02T09:45:19.000Z",
    "size": 8,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "interview-code-challenges",
    "url": "https://github.com/guidesmiths/interview-code-challenges",
    "description": "A set of code challenges for GuideSmiths interviews",
    "updatedAt": "2021-02-23T19:13:22.000Z",
    "size": 5094,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "gs-component-library",
    "url": "https://github.com/guidesmiths/gs-component-library",
    "description": "React reusable component library",
    "updatedAt": "2021-02-21T08:05:02.000Z",
    "size": 274,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "open-badges",
    "url": "https://github.com/guidesmiths/open-badges",
    "description": "Slack notifications from badgr.io badges. Let's add gamification to your team!",
    "updatedAt": "2021-02-16T16:15:26.000Z",
    "size": 349,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "gs-job-offers",
    "url": "https://github.com/guidesmiths/gs-job-offers",
    "description": "Job offers available for Guidesmiths",
    "updatedAt": "2021-02-16T16:10:22.000Z",
    "size": 1,
    "hasIssues": false,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "systemic-knex",
    "url": "https://github.com/guidesmiths/systemic-knex",
    "description": "A systemic Knex component",
    "updatedAt": "2021-02-15T12:07:40.000Z",
    "size": 19,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": ".travis.yml"
  },
  {
    "name": "systemic-express",
    "url": "https://github.com/guidesmiths/systemic-express",
    "description": "A systemic express component",
    "updatedAt": "2021-02-14T21:42:54.000Z",
    "size": 38,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "react-form-creator",
    "url": "https://github.com/guidesmiths/react-form-creator",
    "description": null,
    "updatedAt": "2021-01-27T19:02:19.000Z",
    "size": 506,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "service-bus-inspector",
    "url": "https://github.com/guidesmiths/service-bus-inspector",
    "description": "A tool to inspect and manage azure service-bus messages.",
    "updatedAt": "2021-01-15T08:53:23.000Z",
    "size": 2563,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": "azure-pipelines.yml"
  },
  {
    "name": "block-sequence",
    "url": "https://github.com/guidesmiths/block-sequence",
    "description": "A sequential id generator, which grabs blocks of ids rather than just one at a time",
    "updatedAt": "2020-11-13T23:11:07.000Z",
    "size": 655,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "gs-events-agenda",
    "url": "https://github.com/guidesmiths/gs-events-agenda",
    "description": "Event's agenda for the GuideSmiths online meetups 🎫",
    "updatedAt": "2020-11-06T18:18:07.000Z",
    "size": 6444,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "contentful-util",
    "url": "https://github.com/guidesmiths/contentful-util",
    "description": null,
    "updatedAt": "2020-10-31T12:23:19.000Z",
    "size": 125,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "swagger-endpoint-validator",
    "url": "https://github.com/guidesmiths/swagger-endpoint-validator",
    "description": "Validator around swagger generator",
    "updatedAt": "2020-10-22T15:31:12.000Z",
    "size": 1883,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "make-manifest",
    "url": "https://github.com/guidesmiths/make-manifest",
    "description": "Generates a manifest file for a node service",
    "updatedAt": "2020-10-22T13:44:40.000Z",
    "size": 1083,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": ".travis.yml"
  },
  {
    "name": "systemic-pg",
    "url": "https://github.com/guidesmiths/systemic-pg",
    "description": "A systemic pg component",
    "updatedAt": "2020-10-15T10:20:30.000Z",
    "size": 43,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "whoosh",
    "url": "https://github.com/guidesmiths/whoosh",
    "description": "Stream content to/from an SFTP Server",
    "updatedAt": "2020-10-07T12:41:58.000Z",
    "size": 255,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "clean-code-school",
    "url": "https://github.com/guidesmiths/clean-code-school",
    "description": "A collection of refactoring and bad smell examples used for training purposes",
    "updatedAt": "2020-09-21T07:37:48.000Z",
    "size": 1815,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "lambda-auth-api",
    "url": "https://github.com/guidesmiths/lambda-auth-api",
    "description": null,
    "updatedAt": "2020-09-06T15:10:00.000Z",
    "size": 76,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "middleware-auth",
    "url": "https://github.com/guidesmiths/middleware-auth",
    "description": null,
    "updatedAt": "2020-09-04T11:18:42.000Z",
    "size": 18,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "microservice-typescript-boilerplate",
    "url": "https://github.com/guidesmiths/microservice-typescript-boilerplate",
    "description": "Microservice Typescript boilerplate",
    "updatedAt": "2020-08-25T14:46:40.000Z",
    "size": 300,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "service-restaurant-reviews",
    "url": "https://github.com/guidesmiths/service-restaurant-reviews",
    "description": "Mentoring service restaurant backend",
    "updatedAt": "2020-08-10T08:13:35.000Z",
    "size": 743,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "eslint-config-imperative",
    "url": "https://github.com/guidesmiths/eslint-config-imperative",
    "description": "JavaScript Imperative Style is just the stuff that actually matters rather than subjective preferences",
    "updatedAt": "2020-07-30T12:29:08.000Z",
    "size": 9,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "eslint-plugin-imperative",
    "url": "https://github.com/guidesmiths/eslint-plugin-imperative",
    "description": "A set of eslint rules used by JavaScript Imperative Style",
    "updatedAt": "2020-07-30T12:29:08.000Z",
    "size": 5,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "worksmith_rascal",
    "url": "https://github.com/guidesmiths/worksmith_rascal",
    "description": "Rascal activities for worksmith",
    "updatedAt": "2020-07-30T12:29:04.000Z",
    "size": 248,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "stashback",
    "url": "https://github.com/guidesmiths/stashback",
    "description": "A library for stashing and retrieving callbacks",
    "updatedAt": "2020-07-05T17:37:51.000Z",
    "size": 485,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "systemic-slack",
    "url": "https://github.com/guidesmiths/systemic-slack",
    "description": "systemic-slack",
    "updatedAt": "2020-05-25T09:08:28.000Z",
    "size": 127,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "dotnetcore-api",
    "url": "https://github.com/guidesmiths/dotnetcore-api",
    "description": "A .NET Core API example",
    "updatedAt": "2020-05-14T10:03:49.000Z",
    "size": 10,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "sql-params-format",
    "url": "https://github.com/guidesmiths/sql-params-format",
    "description": "Formatter for named sql params",
    "updatedAt": "2020-05-06T07:14:26.000Z",
    "size": 74,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "marv-pg-driver",
    "url": "https://github.com/guidesmiths/marv-pg-driver",
    "description": "A postgres marv driver implementation",
    "updatedAt": "2020-04-04T11:44:23.000Z",
    "size": 409,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "marv-compliance-tests",
    "url": "https://github.com/guidesmiths/marv-compliance-tests",
    "description": "Compliance tests for marv drivers",
    "updatedAt": "2020-04-04T11:42:40.000Z",
    "size": 107,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": ".travis.yml"
  },
  {
    "name": "sdet-yadda-demo",
    "url": "https://github.com/guidesmiths/sdet-yadda-demo",
    "description": "Software Developer In Test Yadda Demo",
    "updatedAt": "2020-04-01T15:40:55.000Z",
    "size": 7,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "seniors",
    "url": "https://github.com/guidesmiths/seniors",
    "description": "A playground to use react",
    "updatedAt": "2020-04-01T15:39:02.000Z",
    "size": 8330,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "basic-programming",
    "url": "https://github.com/guidesmiths/basic-programming",
    "description": null,
    "updatedAt": "2020-04-01T15:36:55.000Z",
    "size": 433,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "offers-api",
    "url": "https://github.com/guidesmiths/offers-api",
    "description": "An API surfacing a relational model from a mysql database",
    "updatedAt": "2020-04-01T15:31:57.000Z",
    "size": 97,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "seniors-app",
    "url": "https://github.com/guidesmiths/seniors-app",
    "description": "A React Native app for seniors",
    "updatedAt": "2020-04-01T15:30:08.000Z",
    "size": 578,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "healthycoin",
    "url": "https://github.com/guidesmiths/healthycoin",
    "description": "A smart contract based application for health",
    "updatedAt": "2020-04-01T15:26:26.000Z",
    "size": 650,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "staff-planning",
    "url": "https://github.com/guidesmiths/staff-planning",
    "description": "A set of scripts to plan staff allocation",
    "updatedAt": "2020-03-28T17:43:34.000Z",
    "size": 469,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "systemic-mysql",
    "url": "https://github.com/guidesmiths/systemic-mysql",
    "description": null,
    "updatedAt": "2020-03-17T15:17:55.000Z",
    "size": 227,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "json-editor-contentful-ui-extension",
    "url": "https://github.com/guidesmiths/json-editor-contentful-ui-extension",
    "description": "Contentful UI extension to show and edit a JSON object using a form",
    "updatedAt": "2020-03-04T15:36:55.000Z",
    "size": 1085,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "systemic-mongodb-memory-server",
    "url": "https://github.com/guidesmiths/systemic-mongodb-memory-server",
    "description": null,
    "updatedAt": "2020-02-24T08:34:43.000Z",
    "size": 9,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "mentoring-app-liber-shop-maintenance",
    "url": "https://github.com/guidesmiths/mentoring-app-liber-shop-maintenance",
    "description": null,
    "updatedAt": "2020-02-19T19:33:11.000Z",
    "size": 5414,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "pg-microuser",
    "url": "https://github.com/guidesmiths/pg-microuser",
    "description": "A container for creating postgres microservice user accounts",
    "updatedAt": "2020-02-06T22:32:36.000Z",
    "size": 6,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "systemic-github-api",
    "url": "https://github.com/guidesmiths/systemic-github-api",
    "description": "A systemic wrapper for github-api",
    "updatedAt": "2020-01-09T15:11:22.000Z",
    "size": 2,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "qs3",
    "url": "https://github.com/guidesmiths/qs3",
    "description": "An AMQP to S3 relay",
    "updatedAt": "2019-12-28T05:37:48.000Z",
    "size": 26,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "systemic-service-runner",
    "url": "https://github.com/guidesmiths/systemic-service-runner",
    "description": "Starts systemic services",
    "updatedAt": "2019-12-13T10:02:57.000Z",
    "size": 21,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "composable-react-pages",
    "url": "https://github.com/guidesmiths/composable-react-pages",
    "description": "Umbrella project for CORP - site builder framework for React",
    "updatedAt": "2019-12-12T20:24:37.000Z",
    "size": 168,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "generator-systemic-microfrontend",
    "url": "https://github.com/guidesmiths/generator-systemic-microfrontend",
    "description": null,
    "updatedAt": "2019-12-12T11:40:18.000Z",
    "size": 0,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "react-native-gesture-handler",
    "url": "https://github.com/guidesmiths/react-native-gesture-handler",
    "description": "Declarative API exposing platform native touch and gesture system to React Native.",
    "updatedAt": "2019-12-11T12:54:53.000Z",
    "size": 33401,
    "hasIssues": false,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "adblock-plus-crx",
    "url": "https://github.com/guidesmiths/adblock-plus-crx",
    "description": "Adblock-Plus crx base64 encoded binary for chromedriver",
    "updatedAt": "2019-12-05T09:35:21.000Z",
    "size": 1029,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "meetup2calendar",
    "url": "https://github.com/guidesmiths/meetup2calendar",
    "description": "Service for adding meetups into a calendar",
    "updatedAt": "2019-11-26T15:52:54.000Z",
    "size": 612,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "world-clock",
    "url": "https://github.com/guidesmiths/world-clock",
    "description": "A world clock underwritten by js-joda and zoneinfo",
    "updatedAt": "2019-11-23T21:26:40.000Z",
    "size": 68,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "node-madgex",
    "url": "https://github.com/guidesmiths/node-madgex",
    "description": "A madgex client library for node",
    "updatedAt": "2019-10-29T14:19:41.000Z",
    "size": 100,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "block-sequence-mongo",
    "url": "https://github.com/guidesmiths/block-sequence-mongo",
    "description": "A mongo implementation of block-sequence",
    "updatedAt": "2019-10-10T11:03:24.000Z",
    "size": 533,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "starscream",
    "url": "https://github.com/guidesmiths/starscream",
    "description": "Asynchronous JSON transformation",
    "updatedAt": "2019-10-09T10:03:20.000Z",
    "size": 61,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "hath-report-spec",
    "url": "https://github.com/guidesmiths/hath-report-spec",
    "description": "Outputs a hath summary in spec like format",
    "updatedAt": "2019-08-09T03:50:02.000Z",
    "size": 7,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": ".travis.yml"
  },
  {
    "name": "generator-react-component",
    "url": "https://github.com/guidesmiths/generator-react-component",
    "description": "A yeoman generator for react components",
    "updatedAt": "2019-08-04T08:26:08.000Z",
    "size": 23,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "generator-react-native",
    "url": "https://github.com/guidesmiths/generator-react-native",
    "description": "A yeoman generator for RN projects",
    "updatedAt": "2019-07-31T14:39:45.000Z",
    "size": 604,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "systemic-mssql",
    "url": "https://github.com/guidesmiths/systemic-mssql",
    "description": "A MSSQL adapter for systemic",
    "updatedAt": "2019-07-09T14:39:10.000Z",
    "size": 16,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "kube-deploy",
    "url": "https://github.com/guidesmiths/kube-deploy",
    "description": null,
    "updatedAt": "2019-06-25T07:14:59.000Z",
    "size": 9,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "aws-sdk-js",
    "url": "https://github.com/guidesmiths/aws-sdk-js",
    "description": "AWS SDK for JavaScript in the browser and Node.js",
    "updatedAt": "2019-06-06T10:53:10.000Z",
    "size": 109877,
    "hasIssues": false,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "json-2-sql",
    "url": "https://github.com/guidesmiths/json-2-sql",
    "description": "Adapters to generate sql tables for different dbs (postgres, redshift...) from json files",
    "updatedAt": "2019-05-29T09:56:28.000Z",
    "size": 67,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "systemic-rabbitmq",
    "url": "https://github.com/guidesmiths/systemic-rabbitmq",
    "description": "A systemic rabbimq component",
    "updatedAt": "2019-05-12T23:25:05.000Z",
    "size": 5,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "react-native-uservoice",
    "url": "https://github.com/guidesmiths/react-native-uservoice",
    "description": "A React Native client for the uservoice SDK",
    "updatedAt": "2019-05-07T10:37:13.000Z",
    "size": 104,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "prepper",
    "url": "https://github.com/guidesmiths/prepper",
    "description": "Prepper is an event based api for pre-processing log events before routing them to your logging framework of choice",
    "updatedAt": "2019-03-28T18:06:30.000Z",
    "size": 123,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "confabulous-vault-loader",
    "url": "https://github.com/guidesmiths/confabulous-vault-loader",
    "description": "A confabulous vault loader",
    "updatedAt": "2019-03-16T19:23:06.000Z",
    "size": 13,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "eslint-config-imperative-es6",
    "url": "https://github.com/guidesmiths/eslint-config-imperative-es6",
    "description": "Imperative ES6 ESLint config. Just the stuff that matters",
    "updatedAt": "2018-10-12T05:11:24.000Z",
    "size": 7,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "groundhog-day",
    "url": "https://github.com/guidesmiths/groundhog-day",
    "description": "An injectable clock for time based tests",
    "updatedAt": "2018-10-07T10:31:43.000Z",
    "size": 29,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "outstanding",
    "url": "https://github.com/guidesmiths/outstanding",
    "description": "Outstanding assists with graceful shutdown of node.js applications.",
    "updatedAt": "2018-10-07T10:22:46.000Z",
    "size": 51,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "acdc",
    "url": "https://github.com/guidesmiths/acdc",
    "description": "Asynchronous JavaScript Object Transformation",
    "updatedAt": "2018-07-31T12:29:19.000Z",
    "size": 294,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "infra-lambdas",
    "url": "https://github.com/guidesmiths/infra-lambdas",
    "description": "Lambdas to help with infrastructure",
    "updatedAt": "2018-07-26T10:11:17.000Z",
    "size": 106,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "financial-api",
    "url": "https://github.com/guidesmiths/financial-api",
    "description": "A REST secure API exposing financial data",
    "updatedAt": "2018-05-16T10:51:02.000Z",
    "size": 61,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "request-token",
    "url": "https://github.com/guidesmiths/request-token",
    "description": "Generates tokens from http requests by converting the method, url and headers to parameters and rendering them with a hogan template.",
    "updatedAt": "2018-04-08T14:28:03.000Z",
    "size": 20,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "confabulous-s3-loader",
    "url": "https://github.com/guidesmiths/confabulous-s3-loader",
    "description": "A confabulous s3 loader",
    "updatedAt": "2017-04-09T01:44:39.000Z",
    "size": 6,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "refdata",
    "url": "https://github.com/guidesmiths/refdata",
    "description": "Client/Server for providing time series refdata",
    "updatedAt": "2016-11-29T15:50:27.000Z",
    "size": 35,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "prerelease-ftw",
    "url": "https://github.com/guidesmiths/prerelease-ftw",
    "description": "Generates a version with prerelease suffix based on the current package version and command line parameters.",
    "updatedAt": "2016-10-10T12:09:21.000Z",
    "size": 10,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "hath-assert",
    "url": "https://github.com/guidesmiths/hath-assert",
    "description": "Assertion helpers for the hath test library",
    "updatedAt": "2016-08-28T21:41:32.000Z",
    "size": 11,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "stringtree-migrate-driver-postgres",
    "url": "https://github.com/guidesmiths/stringtree-migrate-driver-postgres",
    "description": "Postgres stringtree migrate driver",
    "updatedAt": "2016-07-26T14:07:38.000Z",
    "size": 2,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "mr.robot",
    "url": "https://github.com/guidesmiths/mr.robot",
    "description": "For dealing with x-robots-tag",
    "updatedAt": "2016-07-19T01:27:44.000Z",
    "size": 88,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "systemic-domain-runner",
    "url": "https://github.com/guidesmiths/systemic-domain-runner",
    "description": "Starts systemic systems within a domain",
    "updatedAt": "2016-07-07T13:17:08.000Z",
    "size": 6,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "dockerfiles",
    "url": "https://github.com/guidesmiths/dockerfiles",
    "description": "A repository for housing dockerfiles",
    "updatedAt": "2016-07-05T06:49:46.000Z",
    "size": 3,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "confabulous-http-loader",
    "url": "https://github.com/guidesmiths/confabulous-http-loader",
    "description": "A confabulous http loader",
    "updatedAt": "2016-06-26T07:43:29.000Z",
    "size": 6,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "confabulous-postgres-loader",
    "url": "https://github.com/guidesmiths/confabulous-postgres-loader",
    "description": "A confabulous postgres loader",
    "updatedAt": "2016-06-25T14:40:48.000Z",
    "size": 8,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "confabulous-etcd-loader",
    "url": "https://github.com/guidesmiths/confabulous-etcd-loader",
    "description": "A confabulous etcd loader",
    "updatedAt": "2016-06-24T18:22:28.000Z",
    "size": 12,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "release-clerk",
    "url": "https://github.com/guidesmiths/release-clerk",
    "description": "A command line utility for posting release notes as issues to a github shared repository",
    "updatedAt": "2016-05-29T12:59:34.000Z",
    "size": 24,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "block-sequence-postgres",
    "url": "https://github.com/guidesmiths/block-sequence-postgres",
    "description": "A PostgreSQL implementation of block-sequence",
    "updatedAt": "2016-05-02T22:06:14.000Z",
    "size": 35,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "block-sequence-mysql",
    "url": "https://github.com/guidesmiths/block-sequence-mysql",
    "description": "A MySQL implementation of block-sequence",
    "updatedAt": "2016-05-02T18:39:48.000Z",
    "size": 13,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "block-sequence-redis",
    "url": "https://github.com/guidesmiths/block-sequence-redis",
    "description": "A redis implementation of block-sequence",
    "updatedAt": "2016-05-02T00:56:42.000Z",
    "size": 12,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": ".travis.yml"
  },
  {
    "name": "block-sequence-reference",
    "url": "https://github.com/guidesmiths/block-sequence-reference",
    "description": "A reference implementation of block-sequence",
    "updatedAt": "2016-05-02T00:44:55.000Z",
    "size": 4,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "block-sequence-compliance-tests",
    "url": "https://github.com/guidesmiths/block-sequence-compliance-tests",
    "description": "Complicance tests for block sequence implementations",
    "updatedAt": "2016-05-02T00:34:00.000Z",
    "size": 9,
    "hasIssues": true,
    "hasLinter": true,
    "hasTests": false,
    "ci": null
  },
  {
    "name": "worksmith_sftp",
    "url": "https://github.com/guidesmiths/worksmith_sftp",
    "description": "SFTP activities for worksmith",
    "updatedAt": "2015-06-09T08:55:25.000Z",
    "size": 9,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "worksmith_etcd",
    "url": "https://github.com/guidesmiths/worksmith_etcd",
    "description": "Etcd activites for worksmith",
    "updatedAt": "2015-05-26T21:51:02.000Z",
    "size": 22,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "qsftp",
    "url": "https://github.com/guidesmiths/qsftp",
    "description": "An AMQP to SFTP relay",
    "updatedAt": "2015-04-30T07:18:29.000Z",
    "size": 45,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  },
  {
    "name": "httq",
    "url": "https://github.com/guidesmiths/httq",
    "description": "Middleware for bridging HTTP and AMQP",
    "updatedAt": "2015-04-29T09:37:37.000Z",
    "size": 92,
    "hasIssues": true,
    "hasLinter": false,
    "hasTests": true,
    "ci": null
  }
]

export default repos